version: '3'

services:
  php:
    build:
      context: .
      dockerfile: dev.Dockerfile
    container_name: DEMO_PHP
    ports:
      - 8000:8000
    volumes:
      - ./:/app
      - ./docker/docker-php-ext-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    working_dir: /app
    # command: tail -f /dev/null
    command: >
      bash -c "composer install && symfony server:start --no-tls"
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:10.5.8
    container_name: DEMO_MARIADB
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=お前はもう死んでいる
      - MYSQL_USER=megumin
      - MYSQL_PASSWORD=bakuretsu
      - MYSQL_DATABASE=konosuba
